name: Setup Environment

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        type: string
    outputs:
      python-version:
        description: 'Python version'
        value: ${{ inputs.python-version }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev
